version: "3"
services:
  postgres:
    image: postgres:12.5
    container_name: ogre_postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ogre-development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
