name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.0"
      - name: Install modules
        run: yarn install
      - name: Run lint for the client
        run: yarn workspace ogre-client lint
      - name: Run prettier for the client
        run: yarn workspace ogre-client prettier:check
      - name: Run type-check for the client
        run: yarn workspace ogre-client check-type
      - name: Run lint for the server
        run: yarn workspace ogre-server lint
      - name: Run type-check for the server
        run: yarn workspace ogre-server check-type
